version: 2
jobs:
  build:
    parallelism: 3
    working_directory: ~/circle-ci
  docker:
    - image: circleci/ruby:2.6.1
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: bundle
  steps:
    - checkout
    - restore_cache:
      keys:
        - circle-ci-{{ checksum "Gemfile.lock" }}
        - circle-ci-
    - run:
      name: Bundle Install
      command: bundle check --path vendor/bundle || bundle install --deployment
    - run: |
      rspec -fd